openapi: 3.0.0
info:
  title: Galleria API
  description: Galleria API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  # - url: https://devjobs-api-nu3z.onrender.com/api
  #   description: Web server
paths:
  /paintings:
    get:
      summary: Get all paintings
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                error: Bad request parameters
        "500":
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal server error
